# Generated by Django 5.0.6 on 2024-06-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_items_ring'),
    ]

    operations = [
        migrations.CreateModel(
            name='bangles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='neckless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
    ]
