# Generated by Django 5.0.6 on 2024-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bangles_neckless'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangles',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='neckless',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ring',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
