# Generated by Django 5.0.6 on 2024-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_bangles_user_remove_neckless_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
