# Generated by Django 5.0.6 on 2024-06-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cartitem_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
