# Generated by Django 5.0.6 on 2024-06-27 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_review_review_ring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_ring',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ring_reviews', to='shop.ring'),
        ),
    ]
