# Generated by Django 5.0.6 on 2024-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_review_ring_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_ring',
            name='comment',
            field=models.TextField(max_length=5),
        ),
    ]
