# Generated by Django 5.0.6 on 2024-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_review_ring_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_ring',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review_ring',
            name='rating',
            field=models.PositiveBigIntegerField(max_length=5),
        ),
    ]
