# Generated by Django 5.0.6 on 2024-06-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_review_ring_comment_alter_review_ring_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_ring',
            name='rating',
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
