# Generated by Django 5.0.6 on 2024-06-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_review_ring_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangles',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neckless',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ring',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review_ring',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
