# Generated by Django 5.0.6 on 2024-06-28 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_bangles_like_count_neckless_like_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='like_by',
            field=models.ManyToManyField(related_name='liked_rings', to=settings.AUTH_USER_MODEL),
        ),
    ]
