# Generated by Django 5.0.6 on 2024-06-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_ring_like_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ring',
            old_name='like_by',
            new_name='liked_by',
        ),
        migrations.AlterField(
            model_name='ring',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ring',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ring',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
