# Generated by Django 5.0.6 on 2024-07-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_like_by_ring_liked_by_alter_ring_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangles',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='imagges-hover'),
        ),
        migrations.AddField(
            model_name='neckless',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='imagges-hover'),
        ),
        migrations.AddField(
            model_name='ring',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='imagges-hover'),
        ),
    ]
