# Generated by Django 5.0.6 on 2024-07-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_bangles_image_hover_neckless_image_hover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neckless',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='images-hover'),
        ),
    ]
