# Generated by Django 5.0.6 on 2024-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_bangles_image_hover_alter_ring_image_hover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangles',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='images-hover/'),
        ),
        migrations.AlterField(
            model_name='neckless',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='images-hover/'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='images-hover/'),
        ),
    ]
