# Generated by Django 5.0.6 on 2024-07-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_bangles_image_hover_alter_neckless_image_hover_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='neckless',
            new_name='Necklace',
        ),
    ]
