# Generated by Django 5.0.6 on 2024-07-01 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_rename_neckless_necklace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='necklace',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_necklace', to=settings.AUTH_USER_MODEL),
        ),
    ]
