# Generated by Django 5.0.6 on 2024-07-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_review_necklace_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_necklace',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necklace_reviews', to='shop.necklace'),
        ),
    ]
