# Generated by Django 5.0.6 on 2024-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_review_necklace_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_ring',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
