# Generated by Django 5.0.6 on 2024-07-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_review_ring_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_necklace',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
