# Generated by Django 5.0.6 on 2024-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_rename_create_at_review_necklace_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
