# Generated by Django 5.0.6 on 2024-07-07 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_order_created_at_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 7, 13, 13, 30, 86486, tzinfo=datetime.timezone.utc)),
        ),
    ]
