# Generated by Django 5.0.6 on 2024-07-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_remove_orderitem_cart_item_orderitem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
