# Generated by Django 5.0.6 on 2024-07-11 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_bangles_liked_by_review_bangle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_bangle',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bangle_reviews', to='shop.bangles'),
        ),
    ]
