# Generated by Django 5.0.6 on 2024-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_alter_review_bangle_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangles',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
