# Generated by Django 5.0.6 on 2024-07-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_bangles_price_alter_necklace_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangles',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bangles',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ring',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
