# Generated by Django 5.0.6 on 2024-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_bangles_description_alter_bangles_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ring',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
